name: Deploy to Ubuntu Server with SSH
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/deploy.key
          chmod 600 ~/.ssh/deploy.key
          cat >>~/.ssh/config <<END
          Host deploy
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/deploy.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_SERVER_IP }}

      - name: Add remote host to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan ${{ secrets.SSH_SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Deploy to server
        run: |
          scp -r ./build/* deploy:~/deploy/personal-page/

      - name: Restart process
        run: |
          ssh deploy "(
            pm2 startOrRestart ~/deploy/personal-page/index.js --name personal-page
          )"
