name: Test SSH Connection

on:
  push:
    branches:
      - master

jobs:
  test_ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Test SSH Connection
        run: ssh -T ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}
